name: Build HDA and Blackbox HDA

on:
  release:
    types:
      - published

jobs:
  build-hda:
    runs-on: ubuntu-latest
    steps:
      - name: Set version number
        run: |
          echo "event name ${{ github.event_name }}"
          echo "event ${{ github.event.release.prerelease }}"

      - name: github.event.release.prerelease
        if: 'github.event.release.prerelease'
        run: echo "pre-release"
